# Generated by Django 4.1.3 on 2022-12-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new1', models.CharField(max_length=100, null=True)),
                ('new2', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
