# Generated by Django 4.1.3 on 2022-12-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
